export interface Client {
  pds: string,
  contrat_num_fct: number,
  pds_site_type_fct: string,
  pds_ai_principal_flag_fct: boolean,
  pds_site_adresse_fct: string,
  pds_site_adresse_cplt_fct: string,
  pds_site_cp_fct: number,
  pds_site_ville_fct: string,
  contractant_nom_fct: string,
  contractant_adresse_fct: string,
  contractant_ville_fct: string,
  contractant_cp_fct: number,
  contractant_pays_fct: string,
  contrat_eso_flag_crm: boolean,
  compteur_diametre_patrimoine: number,
  compteur_acces_patrimoine: string,
  compteur_emplacement_patrimoine: string,
  destinataire_nom_fct: string,
}